//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeskAssembleData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DeskAssemblyEntities : DbContext
    {
        public DeskAssemblyEntities()
            : base("name=DeskAssemblyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Capture> Capture { get; set; }
        public virtual DbSet<Contract> Contract { get; set; }
        public virtual DbSet<Country> Country { get; set; }
        public virtual DbSet<Expense> Expense { get; set; }
        public virtual DbSet<Item> Item { get; set; }
        public virtual DbSet<Movement> Movement { get; set; }
        public virtual DbSet<Order> Order { get; set; }
        public virtual DbSet<Team> Team { get; set; }
        public virtual DbSet<WareHouse> WareHouse { get; set; }
    }
}
