//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeskAssembleData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movement
    {
        public int MovementId { get; set; }
        public int ItemId { get; set; }
        public int ContractId { get; set; }
        public System.DateTime Datetime { get; set; }
        public bool IsIn { get; set; }
        public int WareHouseId { get; set; }
        public int Quantity { get; set; }
    
        public virtual Contract Contract { get; set; }
        public virtual WareHouse WareHouse { get; set; }
        public virtual Item Item { get; set; }
    }
}
